# Generated by Django 3.0.5 on 2021-07-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineas_Aereas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200)),
                ('Linea_Aerea', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajeros_2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Pasajero', models.IntegerField()),
                ('Pasajero', models.CharField(max_length=200)),
                ('Edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasajeros_2017',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Pasajero', models.IntegerField()),
                ('Pasajero', models.CharField(max_length=200)),
                ('Edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos_2016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cve_LA', models.CharField(max_length=10)),
                ('Viaje', models.DateTimeField()),
                ('Clase', models.CharField(max_length=20)),
                ('Precio', models.IntegerField()),
                ('Ruta', models.CharField(max_length=100)),
                ('Cve_Cliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos_2017',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cve_LA', models.CharField(max_length=10)),
                ('Viaje', models.DateTimeField()),
                ('Clase', models.CharField(max_length=20)),
                ('Precio', models.IntegerField()),
                ('Ruta', models.CharField(max_length=100)),
                ('Cve_Cliente', models.IntegerField()),
            ],
        ),
    ]
