# Generated by Django 3.1.3 on 2021-08-01 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vuelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajeros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Pasajero', models.IntegerField(help_text='Identificador unico del pasajero', unique=True)),
                ('Pasajero', models.CharField(help_text='Nombre del pasajero', max_length=200)),
                ('Edad', models.IntegerField(help_text='Edad actual del pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Viaje', models.DateTimeField(help_text='Fecha del viaje')),
                ('Clase', models.CharField(help_text='Clase del vuelo', max_length=20)),
                ('Precio', models.IntegerField(help_text='Costo del viaje')),
                ('Ruta', models.CharField(help_text='Origen-Destino', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Pasajeros_2016',
        ),
        migrations.DeleteModel(
            name='Pasajeros_2017',
        ),
        migrations.DeleteModel(
            name='Vuelos_2016',
        ),
        migrations.DeleteModel(
            name='Vuelos_2017',
        ),
        migrations.AlterField(
            model_name='lineas_aereas',
            name='Code',
            field=models.CharField(help_text='Codigo de la aerolinea', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='lineas_aereas',
            name='Linea_Aerea',
            field=models.CharField(help_text='Nombre de la aerolinea', max_length=200),
        ),
        migrations.AddField(
            model_name='vuelos',
            name='Linea_aerea',
            field=models.ForeignKey(default='OT', help_text='Referencia a una Lineas_Aereas', null=True, on_delete=django.db.models.deletion.CASCADE, to='Vuelos.lineas_aereas', to_field='Code'),
        ),
        migrations.AddField(
            model_name='vuelos',
            name='Pasajero_vuelo',
            field=models.ForeignKey(help_text='Referencia a un pasajero', on_delete=django.db.models.deletion.CASCADE, to='Vuelos.pasajeros', to_field='ID_Pasajero'),
        ),
    ]
